-- Migration 009: VIEW-ONLY seed of existing homepage banners + 3 existing forms
-- Auto-generated by db/migrations/009_seed_existing.js
-- Live frontend is NOT modified by this seed.

-- Banners (3 homepage hero slides)
-- Wipe existing seed copies so re-running stays idempotent for the seeded sort_order range
DELETE FROM hero_banners WHERE eyebrow IN ('Consulting • Mentoring • Empowerment','Corporate Strategy • Leadership','Success Factors • Mentoring');

INSERT INTO hero_banners (sort_order,eyebrow,heading,heading_accent,description,btn1_text,btn1_link,btn2_text,btn2_link,bg_type,bg_image_url,overlay_opacity,text_align,text_color,is_active) VALUES (10,'Consulting • Mentoring • Empowerment','Empowering','Business Growth & Sustainability','We partner with boards, entrepreneurs and academic institutions to deliver visible, measurable outcomes through focused involvement and innovative strategy.','Explore Services','/services.html','Get in Touch','/reach-us.html','image_overlay','/assets/gallery-corporate-1.jpg',0.55,'left','#ffffff',0);
INSERT INTO hero_banners (sort_order,eyebrow,heading,heading_accent,description,btn1_text,btn1_link,btn2_text,btn2_link,bg_type,bg_image_url,overlay_opacity,text_align,text_color,is_active) VALUES (20,'Corporate Strategy • Leadership','Innovative','Strategy for Modern Enterprise','Transforming complex challenges into sustainable growth opportunities through our decades of industry experience and academic research.','CXO Conclave','/cxo-conclave.html','Mentoring','/mentoring-form.html','image_overlay','/assets/hero-innovation.png',0.55,'left','#ffffff',0);
INSERT INTO hero_banners (sort_order,eyebrow,heading,heading_accent,description,btn1_text,btn1_link,btn2_text,btn2_link,bg_type,bg_image_url,overlay_opacity,text_align,text_color,is_active) VALUES (30,'Success Factors • Mentoring','Cultivating','Professional Excellence','Empowering individuals and institutions with the right Success Factors to thrive in today''s competitive global landscape.','About Our Team','/profile.html','Connect With Us','/mentoring-form.html','image_overlay','/assets/gallery-skyscrapers.avif',0.55,'left','#ffffff',0);

-- Forms (mirrors of existing static-HTML forms)
INSERT INTO forms (slug, name, description, success_message, button_text, is_active) VALUES
  ('contact', 'Contact Us (mirror of /reach-us.html)', 'Mirror of the form on the live /reach-us.html page. Editing here does NOT yet change the live form — the static HTML page would need to be rewired to use this form definition.', 'Thanks — we''ll get back to you shortly.', 'Send Message', 0)
  ON CONFLICT(slug) DO UPDATE SET
    name=excluded.name, description=excluded.description, success_message=excluded.success_message,
    button_text=excluded.button_text, updated_at=datetime('now');

-- Reset fields for contact
DELETE FROM form_fields WHERE form_id = (SELECT id FROM forms WHERE slug = 'contact');
INSERT INTO form_fields (form_id, label, name, type, placeholder, options_json, is_required, sort_order) VALUES
  ((SELECT id FROM forms WHERE slug = 'contact'),
   'Your full name', 'name', 'text',
   'Your full name', NULL, 1, 10);
INSERT INTO form_fields (form_id, label, name, type, placeholder, options_json, is_required, sort_order) VALUES
  ((SELECT id FROM forms WHERE slug = 'contact'),
   'Phone number', 'phone', 'phone',
   'Your phone number', NULL, 0, 20);
INSERT INTO form_fields (form_id, label, name, type, placeholder, options_json, is_required, sort_order) VALUES
  ((SELECT id FROM forms WHERE slug = 'contact'),
   'Email address', 'email', 'email',
   'Your email address', NULL, 1, 30);
INSERT INTO form_fields (form_id, label, name, type, placeholder, options_json, is_required, sort_order) VALUES
  ((SELECT id FROM forms WHERE slug = 'contact'),
   'Message', 'message', 'textarea',
   'Your message…', NULL, 1, 40);

INSERT INTO forms (slug, name, description, success_message, button_text, is_active) VALUES
  ('mentoring', 'Mentoring Enquiry (mirror of /mentoring-form.html)', 'Mirror of the form on /mentoring-form.html. Edit here for reference; live form is still the static HTML version.', 'Thanks — we will reach out shortly.', 'Submit Enquiry', 0)
  ON CONFLICT(slug) DO UPDATE SET
    name=excluded.name, description=excluded.description, success_message=excluded.success_message,
    button_text=excluded.button_text, updated_at=datetime('now');

-- Reset fields for mentoring
DELETE FROM form_fields WHERE form_id = (SELECT id FROM forms WHERE slug = 'mentoring');
INSERT INTO form_fields (form_id, label, name, type, placeholder, options_json, is_required, sort_order) VALUES
  ((SELECT id FROM forms WHERE slug = 'mentoring'),
   'First name', 'first_name', 'text',
   'First name', NULL, 1, 10);
INSERT INTO form_fields (form_id, label, name, type, placeholder, options_json, is_required, sort_order) VALUES
  ((SELECT id FROM forms WHERE slug = 'mentoring'),
   'Last name', 'last_name', 'text',
   'Last name', NULL, 1, 20);
INSERT INTO form_fields (form_id, label, name, type, placeholder, options_json, is_required, sort_order) VALUES
  ((SELECT id FROM forms WHERE slug = 'mentoring'),
   'Email address', 'email', 'email',
   'you@mail.com', NULL, 1, 30);
INSERT INTO form_fields (form_id, label, name, type, placeholder, options_json, is_required, sort_order) VALUES
  ((SELECT id FROM forms WHERE slug = 'mentoring'),
   'Mobile number', 'mobile', 'phone',
   'Phone number', NULL, 1, 40);
INSERT INTO form_fields (form_id, label, name, type, placeholder, options_json, is_required, sort_order) VALUES
  ((SELECT id FROM forms WHERE slug = 'mentoring'),
   'Designation', 'designation', 'text',
   'Designation', NULL, 0, 50);
INSERT INTO form_fields (form_id, label, name, type, placeholder, options_json, is_required, sort_order) VALUES
  ((SELECT id FROM forms WHERE slug = 'mentoring'),
   'Organisation', 'organisation', 'text',
   'Organisation', NULL, 0, 60);
INSERT INTO form_fields (form_id, label, name, type, placeholder, options_json, is_required, sort_order) VALUES
  ((SELECT id FROM forms WHERE slug = 'mentoring'),
   'Organisation type', 'org_type', 'select',
   '', '["MSME","Startup","Others"]', 1, 70);
INSERT INTO form_fields (form_id, label, name, type, placeholder, options_json, is_required, sort_order) VALUES
  ((SELECT id FROM forms WHERE slug = 'mentoring'),
   'Message', 'message', 'textarea',
   'Your message', NULL, 1, 80);

INSERT INTO forms (slug, name, description, success_message, button_text, is_active) VALUES
  ('cxo-registration', 'CXO Conclave Registration (mirror of /cxo-registration.html)', 'Mirror of the CXO registration form. View-only reference — live form is the static HTML page with reactive amount calculation.', 'Thanks — your CXO Conclave registration has been received.', 'Submit Registration', 0)
  ON CONFLICT(slug) DO UPDATE SET
    name=excluded.name, description=excluded.description, success_message=excluded.success_message,
    button_text=excluded.button_text, updated_at=datetime('now');

-- Reset fields for cxo-registration
DELETE FROM form_fields WHERE form_id = (SELECT id FROM forms WHERE slug = 'cxo-registration');
INSERT INTO form_fields (form_id, label, name, type, placeholder, options_json, is_required, sort_order) VALUES
  ((SELECT id FROM forms WHERE slug = 'cxo-registration'),
   'Registration type', 'reg_type', 'radio',
   '', '["Individual","Business"]', 1, 10);
INSERT INTO form_fields (form_id, label, name, type, placeholder, options_json, is_required, sort_order) VALUES
  ((SELECT id FROM forms WHERE slug = 'cxo-registration'),
   'Nomination Type & Package', 'programme', 'select',
   '', '["Individual Nomination - ₹68,000","Corporate (3 Participants) - ₹1,95,000","Corporate (5 Participants) - ₹3,10,000","Corporate (10 Participants) - ₹5,80,000"]', 1, 20);
INSERT INTO form_fields (form_id, label, name, type, placeholder, options_json, is_required, sort_order) VALUES
  ((SELECT id FROM forms WHERE slug = 'cxo-registration'),
   'Title', 'title', 'select',
   '', '["Mr.","Ms.","Mrs.","Dr.","Prof."]', 0, 30);
INSERT INTO form_fields (form_id, label, name, type, placeholder, options_json, is_required, sort_order) VALUES
  ((SELECT id FROM forms WHERE slug = 'cxo-registration'),
   'First name', 'first_name', 'text',
   '', NULL, 1, 40);
INSERT INTO form_fields (form_id, label, name, type, placeholder, options_json, is_required, sort_order) VALUES
  ((SELECT id FROM forms WHERE slug = 'cxo-registration'),
   'Middle name', 'middle_name', 'text',
   '', NULL, 0, 50);
INSERT INTO form_fields (form_id, label, name, type, placeholder, options_json, is_required, sort_order) VALUES
  ((SELECT id FROM forms WHERE slug = 'cxo-registration'),
   'Last name', 'last_name', 'text',
   '', NULL, 1, 60);
INSERT INTO form_fields (form_id, label, name, type, placeholder, options_json, is_required, sort_order) VALUES
  ((SELECT id FROM forms WHERE slug = 'cxo-registration'),
   'Date of birth', 'dob', 'date',
   '', NULL, 0, 70);
INSERT INTO form_fields (form_id, label, name, type, placeholder, options_json, is_required, sort_order) VALUES
  ((SELECT id FROM forms WHERE slug = 'cxo-registration'),
   'Designation', 'designation', 'text',
   '', NULL, 1, 80);
INSERT INTO form_fields (form_id, label, name, type, placeholder, options_json, is_required, sort_order) VALUES
  ((SELECT id FROM forms WHERE slug = 'cxo-registration'),
   'Company', 'company', 'text',
   '', NULL, 1, 90);
INSERT INTO form_fields (form_id, label, name, type, placeholder, options_json, is_required, sort_order) VALUES
  ((SELECT id FROM forms WHERE slug = 'cxo-registration'),
   'Industry', 'industry', 'text',
   '', NULL, 0, 100);
INSERT INTO form_fields (form_id, label, name, type, placeholder, options_json, is_required, sort_order) VALUES
  ((SELECT id FROM forms WHERE slug = 'cxo-registration'),
   'Specialization', 'specialization', 'text',
   '', NULL, 0, 110);
INSERT INTO form_fields (form_id, label, name, type, placeholder, options_json, is_required, sort_order) VALUES
  ((SELECT id FROM forms WHERE slug = 'cxo-registration'),
   'Office address', 'addr_office', 'textarea',
   '', NULL, 0, 120);
INSERT INTO form_fields (form_id, label, name, type, placeholder, options_json, is_required, sort_order) VALUES
  ((SELECT id FROM forms WHERE slug = 'cxo-registration'),
   'Office PIN', 'pin_office', 'text',
   '', NULL, 0, 130);
INSERT INTO form_fields (form_id, label, name, type, placeholder, options_json, is_required, sort_order) VALUES
  ((SELECT id FROM forms WHERE slug = 'cxo-registration'),
   'Residence address', 'addr_residence', 'textarea',
   '', NULL, 0, 140);
INSERT INTO form_fields (form_id, label, name, type, placeholder, options_json, is_required, sort_order) VALUES
  ((SELECT id FROM forms WHERE slug = 'cxo-registration'),
   'Residence PIN', 'pin_residence', 'text',
   '', NULL, 0, 150);
INSERT INTO form_fields (form_id, label, name, type, placeholder, options_json, is_required, sort_order) VALUES
  ((SELECT id FROM forms WHERE slug = 'cxo-registration'),
   'Telephone', 'tel', 'phone',
   '', NULL, 0, 160);
INSERT INTO form_fields (form_id, label, name, type, placeholder, options_json, is_required, sort_order) VALUES
  ((SELECT id FROM forms WHERE slug = 'cxo-registration'),
   'Mobile', 'mobile', 'phone',
   '', NULL, 1, 170);
INSERT INTO form_fields (form_id, label, name, type, placeholder, options_json, is_required, sort_order) VALUES
  ((SELECT id FROM forms WHERE slug = 'cxo-registration'),
   'Office email', 'email_office', 'email',
   '', NULL, 1, 180);
INSERT INTO form_fields (form_id, label, name, type, placeholder, options_json, is_required, sort_order) VALUES
  ((SELECT id FROM forms WHERE slug = 'cxo-registration'),
   'Personal email', 'email_permanent', 'email',
   '', NULL, 0, 190);
INSERT INTO form_fields (form_id, label, name, type, placeholder, options_json, is_required, sort_order) VALUES
  ((SELECT id FROM forms WHERE slug = 'cxo-registration'),
   'IOD member?', 'iod_member', 'radio',
   '', '["Yes","No"]', 0, 200);
INSERT INTO form_fields (form_id, label, name, type, placeholder, options_json, is_required, sort_order) VALUES
  ((SELECT id FROM forms WHERE slug = 'cxo-registration'),
   'Amount payable (excl. GST)', 'amount', 'text',
   'Auto-filled from package selection', NULL, 0, 210);
INSERT INTO form_fields (form_id, label, name, type, placeholder, options_json, is_required, sort_order) VALUES
  ((SELECT id FROM forms WHERE slug = 'cxo-registration'),
   'Date', 'date', 'date',
   '', NULL, 0, 220);
